import type { Template } from './types';

export const TEMPLATES: Template[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean and simple — just the essentials',
    icon: '✨',
    activeSections: ['title', 'description', 'installation', 'license'],
    data: {
      projectTitle: 'My Project',
      description: 'A brief description of what this project does.',
      installation: '```bash\nnpm install my-project\n```',
      license: 'MIT',
    },
  },
  {
    id: 'standard',
    name: 'Standard',
    description: 'Balanced for most projects with all key sections',
    icon: '📦',
    activeSections: ['title', 'description', 'badges', 'features', 'installation', 'usage', 'contributing', 'license', 'author'],
    data: {
      projectTitle: 'My Awesome Project',
      description: 'A full-featured application that solves real-world problems with elegance and efficiency.',
      badges: [
        { type: 'license', label: 'License', value: 'MIT', color: 'green' },
        { type: 'version', label: 'Version', value: '1.0.0', color: 'blue' },
      ],
      features: [
        '🚀 Lightning-fast performance',
        '🎨 Beautiful, intuitive interface',
        '🔒 Secure by default',
        '📱 Responsive across all devices',
      ],
      installation: '```bash\n# Clone the repository\ngit clone https://github.com/username/my-project.git\n\n# Navigate to the directory\ncd my-project\n\n# Install dependencies\nnpm install\n\n# Start the development server\nnpm run dev\n```',
      usage: '```javascript\nimport { MyProject } from \'my-project\';\n\nconst app = new MyProject();\napp.start();\n```',
      contributing: 'Contributions are welcome! Please feel free to submit a Pull Request.',
      license: 'MIT',
      authorName: 'Your Name',
      authorGithub: 'yourusername',
    },
  },
  {
    id: 'detailed',
    name: 'Detailed',
    description: 'Comprehensive with every section filled in',
    icon: '📋',
    activeSections: ['title', 'description', 'badges', 'banner', 'features', 'techStack', 'installation', 'usage', 'contributing', 'license', 'author'],
    data: {
      projectTitle: 'Enterprise App',
      description: 'A production-grade enterprise application built with modern technologies. Features comprehensive documentation, thorough testing, and enterprise-level security.',
      badges: [
        { type: 'license', label: 'License', value: 'Apache-2.0', color: 'red' },
        { type: 'version', label: 'Version', value: '2.5.0', color: 'blue' },
        { type: 'build', label: 'Build', value: 'passing', color: 'brightgreen' },
        { type: 'coverage', label: 'Coverage', value: '95%', color: 'green' },
      ],
      features: [
        '🏗️ Enterprise-grade architecture',
        '🔐 OAuth 2.0 / JWT authentication',
        '📊 Real-time analytics dashboard',
        '🌐 Multi-language support (i18n)',
        '⚡ Optimized for performance at scale',
        '🧪 98% test coverage',
      ],
      techStack: [
        { name: 'React' },
        { name: 'TypeScript' },
        { name: 'Node.js' },
        { name: 'PostgreSQL' },
        { name: 'Redis' },
        { name: 'Docker' },
      ],
      installation: '```bash\n# Prerequisites\n# - Node.js >= 18\n# - PostgreSQL >= 14\n# - Redis >= 7\n\n# Clone the repository\ngit clone https://github.com/org/enterprise-app.git\ncd enterprise-app\n\n# Install dependencies\nnpm install\n\n# Set up environment variables\ncp .env.example .env\n\n# Run database migrations\nnpm run db:migrate\n\n# Start the development server\nnpm run dev\n```',
      usage: '```bash\n# Development\nnpm run dev\n\n# Production build\nnpm run build\n\n# Run tests\nnpm test\n\n# Lint code\nnpm run lint\n```',
      contributing: '1. Fork the repository\n2. Create your feature branch (`git checkout -b feature/amazing-feature`)\n3. Commit your changes (`git commit -m \'Add amazing feature\'`)\n4. Push to the branch (`git push origin feature/amazing-feature`)\n5. Open a Pull Request',
      license: 'Apache-2.0',
      authorName: 'Engineering Team',
      authorGithub: 'org',
      authorEmail: 'team@org.com',
    },
  },
  {
    id: 'opensource',
    name: 'Open Source',
    description: 'Community-ready with contributor guidelines',
    icon: '🌍',
    activeSections: ['title', 'description', 'badges', 'features', 'installation', 'usage', 'contributing', 'license', 'author'],
    data: {
      projectTitle: 'Open Source Tool',
      description: '🎉 An open-source tool built by the community, for the community. We welcome all contributors!',
      badges: [
        { type: 'license', label: 'License', value: 'MIT', color: 'green' },
        { type: 'version', label: 'Version', value: '0.1.0', color: 'orange' },
        { type: 'prs', label: 'PRs', value: 'Welcome', color: 'brightgreen' },
        { type: 'stars', label: 'Stars', value: '⭐', color: 'yellow' },
      ],
      features: [
        '🆓 Free and open source forever',
        '🤝 Community-driven development',
        '📖 Comprehensive documentation',
        '🧩 Plugin and extension system',
        '🌐 Works everywhere',
      ],
      installation: '```bash\n# Using npm\nnpm install open-source-tool\n\n# Using yarn\nyarn add open-source-tool\n\n# Using pnpm\npnpm add open-source-tool\n```',
      usage: '```javascript\nimport { Tool } from \'open-source-tool\';\n\nconst tool = new Tool({ option: true });\ntool.run();\n```',
      contributing: '## How to Contribute\n\nWe love your input! We want to make contributing to this project as easy and transparent as possible, whether it\'s:\n\n- Reporting a bug\n- Discussing the current state of the code\n- Submitting a fix\n- Proposing new features\n- Becoming a maintainer\n\n### Steps\n1. Fork the repo and create your branch from `main`\n2. If you\'ve added code, add tests\n3. If you\'ve changed APIs, update the docs\n4. Ensure the test suite passes\n5. Submit a pull request!',
      license: 'MIT',
      authorName: 'Community',
      authorGithub: 'community-org',
    },
  },
];
